version: "3.0"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    ports:
      - "8080:8080"

  # s3cmd --no-ssl --host localhost:9000 --access_key minioadmin --secret_key minioadmin ls
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
#  # ftp -np localhost 2121
#  ftp:
#    image: stilliard/pure-ftpd
#    ports:
#      - "2020:20"
#      - "2121:21"
#      - "30000-30009:30000-30009"
#    environment:
#      PUBLICHOST: ftp
#      FTP_USER_NAME: ftp
#      FTP_USER_PASS: ftp
#      FTP_USER_HOME: /home/ftp
#  # sftp -P 2222 sftp@localhost
#  sftp:
#    image: atmoz/sftp
#    ports:
#      - "2222:22"
#    command: sftp:sftp
